import "@/globals.scss";
import Head from "next/head";

export const metadata = {
  title: "comp",
  description: "Generated by crocode",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
