import "@/globals.scss";

export const metadata = {
  title: "SDSADSA",
  description: "Generated by crocode",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
