import "@/globals.scss";
import { IBM_Plex_Sans } from "next/font/google";

const font = IBM_Plex_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
});

export const metadata = {
  title: "BeautyBox",
  description: "Generated by crocode",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body>{children}</body>
    </html>
  );
}
